sudo: required
dist: zesty
language: node_js
node_js:
  - '7'

branches:
  only:
  - master
  - dev

before_install:
- cd backend

install:
- npm install
- cd ..

before_script:
- npm install -g @angular/cli
- npm install -g karma
- npm install

script: 
- ng build
- cd backend
- npm start
- npm test
